#!/bin/bash
APP='strut'

# Retrieve arguments
domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)
public_site=$(sudo yunohost app setting $APP public_site)


### Execute potential SQL statements here

# Copy files to the right place
final_path=/var/www/$APP
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Set permissions to roundcube directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*

sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/$APP.conf


sudo service php5-fpm restart
# Reload Nginx
sudo service nginx reload
sudo yunohost app setting $APP skipped_uris -v "/"  
if [ $public_site = "No" ];
then              
	sudo yunohost app setting $APP protected_uris -v "/admin,/index.php,/choix_date.php,/infos_sondage.php,/scripts" 
else              
	sudo yunohost app setting $APP protected_uris -v "/admin,/scripts"
fi
sudo yunohost app ssowatconf
